// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://oofqtfpmkihcetlieflb.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9vZnF0ZnBta2loY2V0bGllZmxiIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODIyMTQwMjgsImV4cCI6MjA5Nzc5MDAyOH0.On26wdw_UQIsesugyq0CcycUdD-mRK3drUFXETVYPe0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});